name: Build & test

on:
  push:
    branches:
      - '*'
    paths-ignore:
      - '**.md'
      - '**.json'
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.json'

jobs:
  build:
    # Skip build if head commit contains 'skip ci'
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    runs-on: macos-latest
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        project: ["healthkit"]

    steps:
      - uses: actions/checkout@v3
    
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11
    
      - name: Setup the flutter environment
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # 'dev', 'alpha', 'beta'
          # flutter-version: '1.12.x' # you can also specify exact version of flutter
      
      - name: Run Flutter doctor
        run: |
          cd ${{ matrix.project }}
          flutter doctor

      - name: Get flutter dependencies
        env:
          PROJECT_DIR: ${{ matrix.project }}
        run: |
          cd $PROJECT_DIR
          flutter pub get
      
      - name: Check for any formatting issues in the code
        env:
          PROJECT_DIR: ${{ matrix.project }}
        run: |
          cd $PROJECT_DIR
          flutter format --set-exit-if-changed .
      
      - name: Statically analyze the Dart code for any errors
        env:
          PROJECT_DIR: ${{ matrix.project }}
        run: |
          cd $PROJECT_DIR
          flutter analyze .
      
      - name: Run widget tests for our flutter project
        env:
          PROJECT_DIR: ${{ matrix.project }}
        run: |
          cd $PROJECT_DIR
          flutter test
      
      - name: Build apk 
        env:
          PROJECT_DIR: ${{ matrix.project }}
        run: |
          cd $PROJECT_DIR
          flutter build apk

      - name: Run iOS build
        env:
          PROJECT_DIR: ${{ matrix.project }}
        run: |
          cd $PROJECT_DIR
          flutter build ios --release --no-codesign

      - name: Upload generated apk to the artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: ${{ matrix.project }}/build/app/outputs/apk/release/app-release.apk
