# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

flutter_application_path = '../flutter_shared'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'Flutter Add To App Sample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Install flutter module
  install_all_flutter_pods(flutter_application_path)
  
  # Pods for Flutter Add To App Sample
  pod 'SwiftProtobuf', '~> 1.4'
end
